export const GET_ERRORS = "GET_ERRORS";
export const GET_PAYMENTS ="GET_PAYMENTS";
export const GET_PAYMENT="GET_PAYMENT";
export const DELETE_PAYMENT="DELETE_PAYMENT";


export const CREATE_NUTRITIONPLAN="CREATE_NUTRITIONPLAN";
export const GET_NUTRITIONPLANS = "GET_NUTRITIONPLANS";
export const GET_NUTRITIONPLAN="GET_NUTRITIONPLAN";
export const DELETE_NUTRITIONPLAN="DELETE_NUTRITIONPLAN";


export const GET_WEIGHTLOGS = "GET_WEIGHTLOGS";
export const GET_WEIGHTLOG = "GET_WEIGHTLOG";
export const DELETE_WEIGHTLOG = "DELETE_WEIGHTLOG";

export const CREATE_DIETPLAN="CREATE_DIETPLAN";
export const GET_DIETPLANS = "GET_DIETPLANS";
export const GET_DIETPLAN="GET_DIETPLAN";
export const DELETE_DIETPLAN="DELETE_DIETPLAN";